print ("""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
""")

fib = [1,2]
even_fib_values = [2]
value = 0
counter = 2
while value < 4000000:
    value = fib[counter - 1] + fib[counter - 2]
    fib.append(value)
    counter += 1
    if value < 4000000:
        if value % 2:
            even_fib_values.append(value)
print (fib)
print (even_fib_values)
